name: Fetch and Convert Markdown

on:
  schedule:
    - cron: '0 */12 * * *' # Runs every 12 hours
  workflow_dispatch: # Allows manual triggering

jobs:
  fetch-and-convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch Markdown content
        run: |
          curl -o content.md "https://rentry.co/freemediafuckyeah/raw"

      - name: Convert Markdown to HTML
        run: |
          npm install marked
          node -e "const marked = require('marked'); const fs = require('fs'); const content = fs.readFileSync('content.md', 'utf8'); fs.writeFileSync('index.html', marked(content));"

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add content.md index.html
          git commit -m "Update Markdown and HTML content"
          git push
